#!/bin/bash

# Define the .env file path
ENV_FILE_PATH=".env"

# Clear the contents of the .env file
> $ENV_FILE_PATH
echo "AZURE_ENV_NAME=$(azd env get-value AZURE_ENV_NAME)" >> $ENV_FILE_PATH
echo "AZURE_LOCATION=$(azd env get-value AZURE_LOCATION)" >> $ENV_FILE_PATH
echo "AZURE_AI_PROJECT_ENDPOINT=$(azd env get-value AZURE_AI_PROJECT_ENDPOINT)" >> $ENV_FILE_PATH
echo "AZURE_AI_FOUNDRY_SERVICE_ENDPOINT=$(azd env get-value AZURE_AI_FOUNDRY_SERVICE_ENDPOINT)" >> $ENV_FILE_PATH
echo "AZURE_RESOURCE_GROUP=$(azd env get-value AZURE_RESOURCE_GROUP)" >> $ENV_FILE_PATH
echo "AZURE_SUBSCRIPTION_ID=$(azd env get-value AZURE_SUBSCRIPTION_ID)" >> $ENV_FILE_PATH
echo "AZURE_TENANT_ID=$(azd env get-value AZURE_TENANT_ID)" >> $ENV_FILE_PATH
echo "AZURE_TEXT_MODEL_NAME=$(azd env get-value AZURE_OPENAI_DEPLOYMENT_NAME)" >> $ENV_FILE_PATH
echo "AZURE_EMBEDDING_MODEL_NAME=$(azd env get-value AZURE_EMBEDDING_MODEL_NAME)" >> $ENV_FILE_PATH
echo "COSMOS_DB_ENDPOINT=$(azd env get-value COSMOS_DB_ENDPOINT)" >> $ENV_FILE_PATH
echo "COSMOS_DB_CONNECTION_STRING=$(azd env get-value COSMOS_DB_CONNECTION_STRING)" >> $ENV_FILE_PATH
echo "COSMOS_DB_DATABASE_NAME=$(azd env get-value COSMOS_DB_DATABASE_NAME)" >> $ENV_FILE_PATH
echo "COSMOS_DB_CHAT_HISTORY_CONTAINER=$(azd env get-value COSMOS_DB_CHAT_HISTORY_CONTAINER)" >> $ENV_FILE_PATH
echo "AZURE_AI_SERVICES_ENDPOINT=$(azd env get-value AZURE_AI_SERVICES_ENDPOINT)" >> $ENV_FILE_PATH
echo "AZURE_AI_SERVICES_KEY=$(azd env get-value AZURE_AI_SERVICES_KEY)" >> $ENV_FILE_PATH
echo "MCP_FLIGHT_SEARCH_TOOL_BASE_URL=$(azd env get-value MCP_FLIGHT_SEARCH_TOOL_BASE_URL)" >> $ENV_FILE_PATH
echo "MCP_FLIGHT_SEARCH_API_KEY=F3FF9AB9-AF9E-42CA-916F-23BEFE7AA546" >> $ENV_FILE_PATH
echo "BACKEND_URL=$(azd env get-value BACKEND_URI)" >> $ENV_FILE_PATH
echo "FRONTEND_URL=$(azd env get-value FRONTEND_URI)" >> $ENV_FILE_PATH
echo "APPLICATIONINSIGHTS_CONNECTION_STRING=$(azd env get-value AZURE_APP_INSIGHTS_CONNECTION_STRING)" >> $ENV_FILE_PATH

exit 0